apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-svc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8081 # The port that the service is running in the cluster
      targetPort: 8081 # The port exposed by the service
  type: NodePort # type of the service.

#  NodePort - can access the application with the help of node IP and Port
#  ClusterIp
#  loadBalancer